services:
  squid:
    image: squid-ssl-arm64
    container_name: squid-proxy
    restart: always
    network_mode: host
    volumes:
      - /srv/appdata/squid/config/squid.conf:/etc/squid/squid.conf
      - /srv/appdata/squid/config/storeid.conf:/etc/squid/storeid.conf
      - /srv/appdata/squid/cache:/var/spool/squid
      - /srv/appdata/squid/ssl:/etc/squid/ssl
      - /srv/appdata/squid/ssl_db:/var/lib/squid/ssl_db
      - /srv/appdata/squid/logs:/var/log/squid
    healthcheck:
      test: [ "CMD-SHELL", "bash -c 'echo > /dev/tcp/127.0.0.1/3128' 2>/dev/null && echo ok || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
